logger_level: "DEBUG"
detector_pacing_sec: 30

storage_base_url: "http://example.com/base-url"
storage_steps: 10

data_len: 1000
mad_detector_window: 5
behavior_detector_lstm_size: 512
behavior_detector_dropout_rate: 0.4
behavior_detector_train_shift: 10
behavior_detector_anomaly_metric_name: 'anomaly_metric'
behavior_detector_path: './behavior_detector'
cusum_threshold: 0.01
cusum_drift: 0.01
cusum_window: 5
anomaly_detector_lstm_size: 512
anomaly_detector_dropout_rate: 0.2
anomaly_detector_epochs: 60
anomaly_detector_shift: 10
anomaly_detector_path: './anomaly_detector'
corr_detector_ssa_window_size: 30
corr_detector_ssa_group: [[0]]
corr_detector_cov_window_size: 5
corr_detector_origin_metric_name: 'origin_metric'

metrics_info_names: []
